name: Build CatCore

on:
    workflow_dispatch:
    push:
        branches: [ main ]
        paths:
            - 'CatCore*/**'
            - '.github/workflows/main.yml'
    pull_request:
        branches: [ main ]
        paths:
            - 'CatCore*/**'
            - '.github/workflows/main.yml'

jobs:
    catcore-shared:
        name: CatCore.Shared
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup dotnet
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 7.0.x
            -   name: Build CatCore.Shared
                id: Build
                run: dotnet build CatCore.Shared --configuration Release
    catcore:
        name: CatCore
        runs-on: windows-latest
        needs: catcore-shared
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup dotnet
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 7.0.x
            -   name: Authenticate with GitHub Package Registry
                run: dotnet nuget update source "ErisApps GH Packages" --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
            -   name: Removed .example suffix from Constants implementation
                shell: pwsh
                run: |
                  Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter 'Constants.user.cs.example' | ForEach-Object {
                    Rename-Item $_.FullName ($_.FullName -replace '\.example$', '')
                  }
            -   name: Find and Replace - Insert CatCore Auth Server URI
                shell: pwsh
                run: |
                  Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter 'Constants.user.cs' | ForEach-Object {
                    (Get-Content $_.FullName) -replace ' \{\{ CATCORE_AUTH_SERVER_URI \}\} ', '${{ secrets.CATCORE_AUTH_SERVER_URI }}' | Set-Content $_.FullName
                  }
            -   name: Find and Replace - Insert Twitch Client Id
                shell: pwsh
                run: |
                  Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter 'Constants.user.cs' | ForEach-Object {
                    (Get-Content $_.FullName) -replace ' \{\{ TWITCH_CLIENT_ID \}\} ', '${{ secrets.TWITCH_CLIENT_ID }}' | Set-Content $_.FullName
                  }
            -   name: Build
                id: Build
                run: dotnet build CatCore --configuration Release
            -   name: Echo Filename
                run: echo $BUILDTEXT \($ASSEMBLYNAME\)
                env:
                    BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                    ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
            -   name: Upload Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: ${{ steps.Build.outputs.filename }}
                    path: ${{ steps.Build.outputs.artifactpath }}
    catcore-azure:
        name: CatCore.Azure
        runs-on: ubuntu-latest
        needs: catcore-shared
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup dotnet
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 7.0.x
            -   name: Build CatCore.Azure
                id: Build
                run: dotnet build CatCore.Azure --configuration Release